import type { PageInfoDisclosureProps } from "@/components/ui/page-info-disclosure";

export const adminPageGuides = {
  applications: { title: "Applications", triggerLabel: "About Applications", description: "Define workloads, then deploy them to your infrastructure.", sections: [{ title: "Build and deploy", content: "An application defines its source, environment, ports, and resources. Use Deployments to release it to a host." }] },
  appCreation: { title: "Create Application", triggerLabel: "About application setup", description: "Set up an application source, configuration, and deployment preferences.", sections: [{ title: "Target selection", content: "You may select a Beacon and region, or leave either automatic. Forge uses the current placement policy and reported node state when it chooses a target." }] },
  nests: { title: "Service Definitions", triggerLabel: "About Service Definitions", description: "Reusable blueprints for game servers.", sections: [{ title: "Nests and eggs", content: "Nests group related games. Each egg defines a container image, startup command, installation script, and configurable variables." }] },
  appTemplates: { title: "App Templates", triggerLabel: "About App Templates", description: "Starting points for the Create Application wizard.", sections: [{ title: "Template storage", content: "Built-in templates are included with Forge. Custom templates are saved in this browser; they are not a shared server-side catalog." }] },
  compatibility: { title: "Legacy Templates", triggerLabel: "About Legacy Templates", description: "Maintain templates used by imported installations.", sections: [{ title: "Choosing a template", content: "Use Service Definitions for new game-server blueprints and App Templates for application presets. Legacy Templates support existing imported configurations." }] },
  registries: { title: "Image Registries", triggerLabel: "About Image Registries", description: "Manage credentials for private container images.", sections: [{ title: "Registry access", content: "Add a registry address and credentials, then verify the connection. Global registries are available to all users." }] },
  forgefile: { title: "Forgefile", triggerLabel: "About Forgefile", description: "Define projects and environments in a versioned manifest.", sections: [{ title: "Validate and apply", content: "Validate your forge.yaml before applying it. Applying updates the project identified by its slug and records a new manifest version." }] },
  tags: { title: "Tags", triggerLabel: "About Tags", description: "Organize resources with reusable, color-coded labels.", sections: [{ title: "Consistent naming", content: "Use short labels for a team, purpose, or environment. A shared vocabulary makes resources easier to find." }] },
  appStore: { title: "App Store", triggerLabel: "About App Store", description: "Browse ready-to-deploy applications and manage their installations.", sections: [{ title: "Installation", content: "Choose an app, review its configuration and resource requirements, and explicitly select the target node. Installed apps appear in the Installed view." }] },
  databases: { title: "Databases", triggerLabel: "About Databases", description: "One place to provision, connect, and operate database workloads.", sections: [{ title: "Database surfaces", content: "Overview summarizes the inventory. Database Hosts stores external MySQL and PostgreSQL connections; the other tabs manage containers, managed databases, and database services." }] },
  catalog: { title: "Service Catalog", triggerLabel: "About Service Catalog", description: "Provision supported databases, caches, queues, and storage services.", sections: [{ title: "Provisioning", content: "Catalog entries describe the available versions, providers, resource requirements, and configuration. Review an entry before choosing its target and provisioning it." }] },
  eggs: { title: "Eggs", triggerLabel: "About Eggs", description: "Runnable game-server definitions within a service family.", sections: [{ title: "Definition contents", content: "An egg specifies container images, startup behavior, installation steps, and the variables exposed when a server is created." }] },
} satisfies Record<string, PageInfoDisclosureProps>;
