#!/usr/bin/env bash
# Generate a production environment file with strong random secrets.
# Usage: ./gen-env.sh [output_path]
#   default output_path: .env.production

set -euo pipefail

OUTPUT_PATH="${1:-.env.production}"

new_secret() {
    local bytes="${1:-32}"
    openssl rand -hex "$bytes"
}

new_uuid() {
    local hex
    hex="$(new_secret 16)"
    printf '%s-%s-%s-%s-%s\n' \
        "${hex:0:8}" "${hex:8:4}" "${hex:12:4}" "${hex:16:4}" "${hex:20:12}"
}

api_secret="$(new_secret 32)"
app_key="$(new_secret 32)"
node_token_id="$(new_secret 8)"
node_token_secret="$(new_secret 32)"
node_token="$node_token_id.$node_token_secret"
node_id="$(new_uuid)"
postgres_password="$(new_secret 24)"
grafana_password="$(new_secret 24)"
master_key="$(new_secret 32)"

if [ -z "${PANEL_DOMAIN:-}" ]; then
    panel_domain="panel.example.com"
    echo "WARNING: PANEL_DOMAIN not set; using placeholder '$panel_domain'." >&2
else
    panel_domain="$PANEL_DOMAIN"
fi

cat > "$OUTPUT_PATH" <<EOF
# Auto-generated by gen-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Review before use. NEVER commit this file.
# Demo seeding is disabled and production startup is fail-closed on secrets.
APP_ENV=production
API_ADDR=:8080
API_AUTH_SECRET=$api_secret
APP_KEY=$app_key
DATABASE_URL=postgres://gamepanel:$postgres_password@postgres:5432/gamepanel?sslmode=disable
REDIS_ADDR=redis:6379
PANEL_URL=https://$panel_domain
PANEL_API_URL=http://api:8080/api/v1
BEACON_PANEL_API_URL=https://$panel_domain/api/v1
DAEMON_ADDR=:9090
DAEMON_DATA_DIR=/srv/game-panel/servers
GAME_SERVERS_HOST_DIR=/srv/game-panel/servers
DAEMON_NODE_ID=$node_id
DAEMON_NODE_TOKEN=$node_token
DAEMON_SFTP_ADDR=:2022
DAEMON_ALLOW_MOCK_RUNTIME=false
LOAD_BALANCER_ENABLED=true
LOAD_BALANCER_BIND_HOST=
LOAD_BALANCER_PORT_MIN=30000
LOAD_BALANCER_PORT_MAX=30100
POSTGRES_DB=gamepanel
POSTGRES_USER=gamepanel
POSTGRES_PASSWORD=$postgres_password
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$grafana_password
BACKUP_ADAPTER=local

# Encryption at Rest (Required when DATABASE_URL is set)
FORGE_MASTER_KEY=$master_key
FORGE_MASTER_KEY_ID=primary
EOF


chmod 600 "$OUTPUT_PATH"
echo "Wrote production environment template to $OUTPUT_PATH"
