param(
    [string]$OutputPath = ".env.production",
    [string]$PanelDomain = $env:PANEL_DOMAIN
)

function New-HexSecret {
    param([int]$Bytes = 32)

    $buffer = New-Object byte[] $Bytes
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($buffer)
    }
    finally {
        $generator.Dispose()
    }
    return -join ($buffer | ForEach-Object { $_.ToString("x2") })
}

if ([string]::IsNullOrWhiteSpace($PanelDomain)) {
    $PanelDomain = "panel.example.com"
    Write-Warning "PANEL_DOMAIN not set; using placeholder '$PanelDomain'."
}

$apiSecret = New-HexSecret
$appKey = New-HexSecret
$nodeTokenId = New-HexSecret 8
$nodeTokenSecret = New-HexSecret 32
$nodeToken = "$nodeTokenId.$nodeTokenSecret"
$nodeId = [Guid]::NewGuid().ToString()
$postgresPassword = New-HexSecret 24
$grafanaPassword = New-HexSecret 24
$masterKey = New-HexSecret 32

@"
# Auto-generated by gen-env.ps1. Review before use. NEVER commit this file.
# Demo seeding is disabled and production startup is fail-closed on secrets.
APP_ENV=production
API_ADDR=:8080
API_AUTH_SECRET=$apiSecret
APP_KEY=$appKey
DATABASE_URL=postgres://gamepanel:$postgresPassword@postgres:5432/gamepanel?sslmode=disable
REDIS_ADDR=redis:6379
PANEL_URL=https://$PanelDomain
PANEL_API_URL=http://api:8080/api/v1
BEACON_PANEL_API_URL=https://$PanelDomain/api/v1
DAEMON_ADDR=:9090
DAEMON_DATA_DIR=/srv/game-panel/servers
GAME_SERVERS_HOST_DIR=/srv/game-panel/servers
DAEMON_NODE_ID=$nodeId
DAEMON_NODE_TOKEN=$nodeToken
DAEMON_SFTP_ADDR=:2022
DAEMON_ALLOW_MOCK_RUNTIME=false
LOAD_BALANCER_ENABLED=true
LOAD_BALANCER_BIND_HOST=
LOAD_BALANCER_PORT_MIN=30000
LOAD_BALANCER_PORT_MAX=30100
POSTGRES_DB=gamepanel
POSTGRES_USER=gamepanel
POSTGRES_PASSWORD=$postgresPassword
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$grafanaPassword
BACKUP_ADAPTER=local
FORGE_MASTER_KEY=$masterKey
FORGE_MASTER_KEY_ID=primary
"@ | Set-Content -LiteralPath $OutputPath -Encoding ASCII

Write-Host "Wrote production environment template to $OutputPath"
