ALTER TABLE servers ADD COLUMN IF NOT EXISTS uuid VARCHAR(36);
ALTER TABLE servers ADD COLUMN IF NOT EXISTS uuid_short VARCHAR(8);
ALTER TABLE servers ADD COLUMN IF NOT EXISTS installed_at TIMESTAMPTZ;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS skip_scripts BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS docker_labels JSONB NOT NULL DEFAULT '{}'::jsonb;
