ALTER TABLE eggs ADD COLUMN IF NOT EXISTS config_from UUID REFERENCES eggs(id);
ALTER TABLE eggs ADD COLUMN IF NOT EXISTS copy_script_from UUID REFERENCES eggs(id);
ALTER TABLE eggs ADD COLUMN IF NOT EXISTS update_url TEXT;
ALTER TABLE eggs ADD COLUMN IF NOT EXISTS author VARCHAR(255);
ALTER TABLE eggs ADD COLUMN IF NOT EXISTS features JSONB DEFAULT '[]'::jsonb;
ALTER TABLE eggs ADD COLUMN IF NOT EXISTS startup_commands JSONB DEFAULT '[]'::jsonb;
ALTER TABLE egg_variables ADD COLUMN IF NOT EXISTS sort INT DEFAULT 0;
